name: GitHub CI

on:
  workflow_dispatch:
  schedule:
    - cron: 0 20 * * *

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.check.outputs.build }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo wget -q -O /usr/local/bin/bashbrew https://github.com/docker-library/bashbrew/releases/latest/download/bashbrew-amd64
          sudo chmod +x /usr/local/bin/bashbrew
          sudo chown root:root /usr/local/bin/bashbrew

      - name: Check for changes
        id: check
        run: |
          declare -a changed_apps
          commit_message="build(app): bump app to latest"
          
          chmod +x *.sh
          ./update.sh
          if git status --porcelain -- $app | grep 'M'; then
            echo "build=1" >> $GITHUB_OUTPUT
            git status
            git config --global user.name "${GITHUB_ACTOR}"
            git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git commit -am "${commit_message}" || exit 0
            git push origin HEAD:master
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  trigger-workflows:
    needs: check
    if: needs.check.outputs.build == '1'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'busybox.yml',
              ref: 'master'
            })